version: "3"

services:
    nginx:
        image: nginx:alpine

        volumes:
            - ./public:/usr/share/nginx/html
        labels:
          - "traefik.enable=true" # Enable this Service
          - "traefik.http.routers.hugo.entrypoints=web-secure" # Use SSL
          - "traefik.http.routers.hugo.rule=Host(`me.rebo.ar`)" # URL that traefik match to send request to this services
          - "traefik.http.routers.hugo.tls=true"
          - "traefik.http.routers.hugo.tls.certresolver=le" # Use prod certificates
          - "traefik.http.services.hugo.loadbalancer.server.port=80" # Port where service is listening.
#         - "traefik.http.middlewares.hugo-white.ipwhitelist.sourcerange=127.0.0.1/32,190.246.194.226"
#         - "traefik.http.routers.hugo.middlewares=hugo-white@docker"
          - "traefik.http.routers.hugo.middlewares=status-pages-middleware@docker"
        networks:
          - backend
networks:
  backend:
    external: true
